# Numpy Cheatsheet

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

## Installation

`pip install numpy`

or

`conda install numpy`

## Importing Numpy

In [1]:
import numpy as np

## Creating Arrays

In [2]:
a = np.array([1, 2, 3]) # 1D array
print(a)

[1 2 3]


In [3]:
a = np.array([[1,2,3],[4,5,6]]) # 2D array
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3D array
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


## Initial Placeholders

In [5]:
a = np.arange(2,20,3) # arrays with regularly incrementing values
print(a)

[ 2  5  8 11 14 17]


In [6]:
a = np.linspace(1., 4., 6) # includes the stop number unlike arrange()
print(a)

[1.  1.6 2.2 2.8 3.4 4. ]


In [7]:
a = np.eye(4,5) # creates 2D identity matrix
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [8]:
a = np.diag([1, 2, 3, 4, 5]) # diagonal elements
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [9]:
a = np.vander([1, 2, 3, 4], 2) # vandermonde array
print(a)

[[1 1]
 [2 1]
 [3 1]
 [4 1]]


In [10]:
a = np.zeros((2, 3, 2)) # arrays with zeros
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [11]:
a = np.ones((2, 3, 2)) # arrays with ones
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [12]:
a = np.indices((3,3)) # set of arrays one per dimension with each representing variation in that dimension
print(a)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


## Modifying Arrays

In [13]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:4].copy() # copies elements from another array
print(b)

[1 2 3 4]


In [14]:
a = np.zeros((2,2))
b = np.ones((2,2))
c = np.array([[7,8],[9,5]])
d = np.diag([3,4])
e = np.block([[a, b], [c, d]]) # joins arrays
print(e)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [7. 8. 3. 0.]
 [9. 5. 0. 4.]]


## Inspecting Arrays

In [15]:
e.shape # shape of an array

(4, 4)

In [16]:
len(e) # length of an array

4

In [17]:
e.ndim # dimensions of an array

2

In [18]:
e.size # size or total number of elements of an array

16

In [19]:
e.dtype # data type of an array

dtype('float64')

In [20]:
e.dtype.name # nae of data type of an array

'float64'

In [21]:
e.astype(int) # converting array elements into another data type

array([[0, 0, 1, 1],
       [0, 0, 1, 1],
       [7, 8, 3, 0],
       [9, 5, 0, 4]])

## Array Mathematics

### Array Arithmetic Operations

In [22]:
a = np.array([[6,7],[8,9]])
b = np.array([[1,2],[3,4]])

In [23]:
c = a + b # addition
print(c)

[[ 7  9]
 [11 13]]


In [24]:
c = np.add(a,b)
print(c)

[[ 7  9]
 [11 13]]


In [25]:
c = a - b # subtraction
print(c)

[[5 5]
 [5 5]]


In [26]:
c = np.subtract(a,b) # subtraction
print(c)

[[5 5]
 [5 5]]


In [27]:
c = a/b # division
print(c)

[[6.         3.5       ]
 [2.66666667 2.25      ]]


In [28]:
c = np.divide(a,b) # division
print(c)

[[6.         3.5       ]
 [2.66666667 2.25      ]]


In [29]:
c = a * b # multiplication
print(c)

[[ 6 14]
 [24 36]]


In [30]:
c = np.multiply(a,b) # multiplication
print(c)

[[ 6 14]
 [24 36]]


In [31]:
np.exp(a) # exponentiation

array([[ 403.42879349, 1096.63315843],
       [2980.95798704, 8103.08392758]])

In [32]:
np.sqrt(b) # square root

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [33]:
np.sin(a) # sine of an array

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849]])

In [34]:
np.cos(a) # co-sine of an array

array([[ 0.96017029,  0.75390225],
       [-0.14550003, -0.91113026]])

In [35]:
np.log(a) # natural log

array([[1.79175947, 1.94591015],
       [2.07944154, 2.19722458]])

In [36]:
a.dot(b) # dot product

array([[27, 40],
       [35, 52]])

### Array Comparison

In [37]:
a == b

array([[False, False],
       [False, False]])

In [38]:
a < 12

array([[ True,  True],
       [ True,  True]])

In [39]:
np.array_equal(a, b)

False

### Aggregate Operations

In [40]:
a.sum() # array-wise sum

30

In [41]:
a.min() # array-wise minimum value

6

In [42]:
a.max(axis=0) # maximum value of a row

array([8, 9])

In [43]:
a.cumsum(axis=1) # cumulative sum

array([[ 6, 13],
       [ 8, 17]], dtype=int32)

In [44]:
a.mean() # mean

7.5

In [45]:
np.median(a) # median

7.5

In [46]:
np.corrcoef(a) # correlation coefficient

array([[1., 1.],
       [1., 1.]])

In [47]:
np.std(a) # standard deviation

1.118033988749895

### Copying Arrays

In [48]:
d = a.view() # create view with same data
print(d)

[[6 7]
 [8 9]]


In [49]:
np.copy(a) # create copy of array

array([[6, 7],
       [8, 9]])

In [50]:
d = a.copy() # create a deep copy of array
print(d)

[[6 7]
 [8 9]]


### Sorting Arrays

In [51]:
x = np.array([9,3,4,7,2,1,8,6,5])

In [52]:
x.sort()
print(x)

[1 2 3 4 5 6 7 8 9]


In [53]:
a.sort(axis=0)
print(a)

[[6 7]
 [8 9]]


## Array Indexing

### Subsetting

In [54]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[2] # returns 3rd element

2

In [56]:
x[-2] # returns 2nd element from the end

8

### Slicing

In [57]:
x[1:7:2] # returns every 2nd elements between 1 and 7, excluding 7

array([1, 3, 5])

In [58]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [59]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

In [60]:
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [62]:
x[np.array([3, 3, 1, 8])] # returns 4th, 4th, 2nd, and 8th elements

array([7, 7, 9, 2])

In [63]:
x[np.array([3, 3, -3, 8])]

array([7, 7, 4, 2])

### Boolean Array Indexing

In [64]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])

In [65]:
x[~np.isnan(x)] # returns elements which are not NaN

array([1., 2., 3.])

### Assigning Values to Indexed Arrays

In [66]:
x = np.arange(10)

In [67]:
x[2:7] = 1 # assigns value 1 to 2nd elements to 6th element
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

## I/O with Numpy

In [68]:
import numpy as np
from io import StringIO

In [69]:
data = u"1, 2, 3\n4, 5, 6"
np.genfromtxt(StringIO(data), delimiter=",") # delimiter define how the splitting should take place

array([[1., 2., 3.],
       [4., 5., 6.]])

In [70]:
data = u"123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [71]:
data = u"1, abc , 2\n 3, xxx, 4"
np.genfromtxt(StringIO(data), delimiter=",", dtype="|U5", autostrip=True) # autostrip removes leading and trailing spaces

array([['1', 'abc', '2'],
       ['3', 'xxx', '4']], dtype='<U5')

In [72]:
data = u"""#
# Skip me !
# Skip me too !
1, 2
3, 4
5, 6 #This is the third line of the data
7, 8
# And here comes the last line
9, 0
"""

np.genfromtxt(StringIO(data), comments="#", delimiter=",")

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [73]:
data = u"\n".join(str(i) for i in range(10))
np.genfromtxt(StringIO(data), skip_header=3, skip_footer=5) # skips 3 elements from start and 5 elements from end

array([3., 4.])

In [74]:
data = u"1 2 3\n4 5 6"
np.genfromtxt(StringIO(data), usecols=(0, -1)) # usecols imports only 1st and last columns

array([[1., 3.],
       [4., 6.]])

## Broadcasting

In [75]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [76]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

## Array Manipulation

In [77]:
a = ([[[1,2,3],[4,5,6],[7,8,9]]])

In [78]:
i = np.transpose(a) # transposes an array
print(i)

[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]

 [[3]
  [6]
  [9]]]


In [79]:
i.T # transposes an array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [80]:
a = np.array([[1,2],[3,4]])
a.ravel() # flattens the array

array([1, 2, 3, 4])

In [81]:
a.reshape(1,-4) # reshapes array without changing data

array([[1, 2, 3, 4]])

In [82]:
a = np.array([1, 2, 3, 4, 5, 6])
a.resize(2, 3) # reshapes array permanently
print(a)

[[1 2 3]
 [4 5 6]]


In [83]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9])
np.append(a,b) # appends data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
x = np.insert(a, 1, 9) # inserts the value 9 as the 2nd element
print(x)

[1 9 2 3 4 5]


In [85]:
np.delete(a,[1]) # deletes the 2nd element

array([1, 3, 4, 5])

In [86]:
np.concatenate((a,b),axis=0) # concatenates arrays

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
x = np.vstack((a,b)) # Stack arrays vertically (row-wise)
print(x)

[[1 2 3]
 [4 5 6]]


In [88]:
y = np.hstack((a,b)) # Stack arrays horizontally (column-wise)
print(y)

[1 2 3 4 5 6]


In [89]:
np.column_stack((a,b)) # Create stacked column-wise arrays

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
a = np.arange(16.0).reshape(4, 4)
np.hsplit(a, 2) # Split the array horizontally at the 3rd element

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [91]:
a = np.arange(9.0).reshape(3, 3)
np.vsplit(a, 1) # Split the array vertically at the 2nd element

[array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])]